-- BASIC TABLES NEEDED BY THE APPLICATION --
-- Dragos 23/11/2016 --
CREATE TABLE EVENTS (ID INT(10) AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255) NOT NULL, TYPE VARCHAR(255) NOT NULL, IMAGE_URL VARCHAR(255), DATE_EVENT TIMESTAMP NOT NULL, ADDRESS VARCHAR(255) NOT NULL, SITE_ID INT(10), FOREIGN KEY(SITE_ID) REFERENCES SITE_TEMPLATES(ID));
CREATE TABLE USERS (ID INT(10) AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL);
CREATE TABLE PLANS (ID INT(10) AUTO_INCREMENT PRIMARY KEY, USER_ID INT(10), PLAN_DATE TIMESTAMP NOT NULL, FOREIGN KEY(USER_ID) REFERENCES USERS(ID));
CREATE TABLE PLAN_EVENTS (PLAN_ID INT(10), EVENT_ID INT(10), PRIMARY KEY(PLAN_ID, EVENT_ID), FOREIGN KEY (PLAN_ID) REFERENCES PLANS(ID), FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID));
