-- BASIC TABLES NEEDED BY THE APPLICATION FOR SITE CRAWLING --
-- Dragos 28/11/2016 --
CREATE TABLE SITE_TEMPLATES (ID INT(10) AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255) NOT NULL, TYPE VARCHAR(255) NOT NULL, LINK VARCHAR(255) NOT NULL);
CREATE TABLE ITEM_TEMPLATES (ID INT(10) AUTO_INCREMENT PRIMARY KEY, SITE_ID INT(10), FOREIGN KEY(SITE_ID) REFERENCES SITE_TEMPLATES(ID));
CREATE TABLE ITEM_CLASSES (ID INT(10) AUTO_INCREMENT PRIMARY KEY, CLASS_NAME VARCHAR(255) NOT NULL, CLASS_TYPE VARCHAR(255) NOT NULL, VALUE_TYPE VARCHAR(255) NOT NULL, VALUE_LOCATION VARCHAR(255), PARENT_CLASS_ID INT(10), ITEM_ID INT(10), FOREIGN KEY(PARENT_CLASS_ID) REFERENCES ITEM_CLASSES(ID), FOREIGN KEY(ITEM_ID) REFERENCES ITEM_TEMPLATES(ID));
