jdbc.driverClassName = org.postgresql.Driver
jdbc.url = jdbc:postgres://ulxcwplhdrwzyi:892a35406857afffa3c032b969a6427fe4e0232c594161bcf00237ba5650d1de@ec2-107-20-226-93.compute-1.amazonaws.com:5432/ddpq2oggvnf0ch
jdbc.username = postgres
jdbc.password = root
