-- SQL SCRIPT FOR CLEARING THE SCHEMA --
DROP TABLE ITEM_CLASSES;
DROP TABLE ITEM_TEMPLATES;
DROP TABLE PLAN_EVENTS;
DROP TABLE PLANS;
DROP TABLE ACCESS_LOGS;
DROP TABLE PREFERENCES;
DROP TABLE USERS;
DROP TABLE EVENTS;
DROP TABLE SITE_TEMPLATES;
DROP TABLE EVENT_TYPE_WORDS;
DROP TABLE KEY_WORDS;
DROP TABLE EVENT_TYPES;
