--INSERT DEVELOPMENT VALUES--
-- Dragos 23/11/2016 --
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('admin', 'admin@admin.com','');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('Dragos', 'dragos@dragos.com','dragos');
INSERT INTO SITE_TEMPLATES (NAME, TYPE, LINK) VALUES('EVENTIM','EVENT','https://eventim.ro');
INSERT INTO ITEM_TEMPLATES (SITE_ID) VALUES ((SELECT ID FROM SITE_TEMPLATES WHERE NAME='EVENTIM'));
INSERT INTO ITEM_CLASSES (CLASS_NAME, CLASS_TYPE, ITEM_ID) VALUES ('nume_event','NAME',(SELECT I.ID FROM ITEM_TEMPLATES I JOIN SITE_TEMPLATES S ON(I.SITE_ID = S.ID) WHERE S.NAME = 'EVENTIM'));
INSERT INTO ITEM_CLASSES (CLASS_NAME, CLASS_TYPE, ITEM_ID) VALUES ('imagine_event','IMAGE',(SELECT I.ID FROM ITEM_TEMPLATES I JOIN SITE_TEMPLATES S ON(I.SITE_ID = S.ID) WHERE S.NAME = 'EVENTIM'));
INSERT INTO ITEM_CLASSES (CLASS_NAME, CLASS_TYPE, ITEM_ID) VALUES ('desc_event','DESCRIPTION',(SELECT I.ID FROM ITEM_TEMPLATES I JOIN SITE_TEMPLATES S ON(I.SITE_ID = S.ID) WHERE S.NAME = 'EVENTIM'));
INSERT INTO ITEM_CLASSES (CLASS_NAME, CLASS_TYPE, ITEM_ID) VALUES ('other_event','OTHER',(SELECT I.ID FROM ITEM_TEMPLATES I JOIN SITE_TEMPLATES S ON(I.SITE_ID = S.ID) WHERE S.NAME = 'EVENTIM'));
INSERT INTO EVENTS (NAME, TYPE, ADDRESS, SITE_ID) VALUES ('Alternosfera', 'CONCERT', 'BUCHAREST', (SELECT ID FROM SITE_TEMPLATES WHERE NAME='EVENTIM'));
INSERT INTO EVENTS (NAME, TYPE, ADDRESS, SITE_ID) VALUES ('Muciacos Gringos', 'TEATRU', 'IASI', (SELECT ID FROM SITE_TEMPLATES WHERE NAME='EVENTIM'));
INSERT INTO EVENTS (NAME, TYPE, ADDRESS, SITE_ID) VALUES ('Vivaldi', 'OPERA', 'BUCHAREST', (SELECT ID FROM SITE_TEMPLATES WHERE NAME='EVENTIM'));
INSERT INTO PLANS (USER_ID) VALUES ((SELECT ID FROM USERS WHERE NAME='Dragos'));
INSERT INTO PLAN_EVENTS VALUES ((SELECT P.ID FROM PLANS P JOIN USERS U ON(P.USER_ID = U.ID) WHERE U.NAME='Dragos'),(SELECT ID FROM EVENTS WHERE NAME='Vivaldi'));
INSERT INTO PLAN_EVENTS VALUES ((SELECT P.ID FROM PLANS P JOIN USERS U ON(P.USER_ID = U.ID) WHERE U.NAME='Dragos'),(SELECT ID FROM EVENTS WHERE NAME='Alternosfera'));
